### PR TITLE
Don't leak JUnit4 and Jetbrains annotations as transitive dependencies

### PR DESCRIPTION
**Pull request by Avalancs**
Testing a solution for #71 . It works for me with `mvn clean install -Dmaven.test.skip=true` but I get some test errors, which I'm not sure if I introduced or if the `develop` branch fails on my machine. Would appreciate it if others tested this as well.

I had to move dom/src/test/java/org/linguafranca/pwdb/kdbx/dom/DomPropertyValueTest.java to the src/test/... folder, but I did not see any other *ValueTest files in other projects under the src folder, so it should have been in the test folder from the beginning?

Also moved MavenRunListener to the src/test folder, which fits how the documentation describes it: https://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html#using-custom-listeners-and-reporters

### CODE REVIEW

**Comment by Avalancs** [comment]
My test failure is related to `database/src/test/java/org/linguafranca/pwdb/PropertyValueTest.java : sealedObjectTest()`. The `THIS_IS_A_SECRET.getBytes()` method uses the platform encoding, and if I run the test from IntelliJ Idea by hand it works fine, but if I run maven then I guess it uses the Windows encoding instead of UTF-8.

I guess it's a maven issue, not a code issue.

**Comment by jorabin** [comment]
1. `THIS_IS_A_SECRET.getBytes()` ... this is a bug, should say `THIS_IS_A_SECRET.getBytes(StandardCharsets.UTF_8)`
2. _Also moved MavenRunListener to the src/test folder_, if you do that then tests on other modules fail, as they can't see the class ...

**Comment by jorabin** [comment]
Thanks for contributing your pull request. As mentioned under my comment on #71 I decided to make some more sweeping changes, hopefully this will serve the purpose you had in mind.

**Comment by Avalancs** [comment]
Yes, this was a proposal, so I'm happy if you can incorporate it in any way.

> Also moved MavenRunListener to the src/test folder, if you do that then tests on other modules fail, as they can't see the class

Interesting, I could do `mvn install` without issues, but sometimes it felt like IntelliJ Idea or maven was not quite compiling with the latest changes I was doing, even if I did a clean...

**Pull request closed without merging**
